### ISSUE TITLE
Material Design, NOT AN ISSUE

### ISSUE THREAD

**Issue by gmorel4** [LTBuses/LTB-android#2] opened 2014-11-10 15:42 UTC
I know this isn't detrimental to the function of the app, but Googles new Material Design philosophy looks pretty awesome.

**Comment by Cyborg572** [comment] 2016-01-16 00:42
![ltbusses-material-1](https://cloud.githubusercontent.com/assets/842710/12369049/e07817a0-bbbf-11e5-930c-628890211a17.png)

I'm starting to experiment a bit with this. All I've done so far is switch to the default material design theme with custom colours for phones that support it. Nothing broke, so that's promising.

**Comment by Cyborg572** [comment] 2016-09-23 04:38
I'm closing this issue as I've moved the project to GitLab.  The migrated version of the issue is here: https://gitlab.com/LTBuses/LTB-android/issues/2

**Closed by Cyborg572** 2016-09-23 04:38 UTC
Labels: enhancement
